# Numpy | Aula 04

## Operações com Arrays Numpy

### Com escalares

In [15]:
import numpy as np

np.random.seed(32)

a1 = np.random.randint(1, 20, 8)

In [19]:
a1

array([12,  6,  8,  4,  6, 11, 10,  5])

In [20]:
a1**2

array([144,  36,  64,  16,  36, 121, 100,  25])

### Entre arrays

In [28]:
a2 = np.random.randint(1, 100, 8)

In [29]:
a2

array([91, 65, 12,  7, 95, 69, 63, 31])

In [31]:
a1 + a2

array([103,  71,  20,  11, 101,  80,  73,  36])

In [33]:
a1 - a2

array([-79, -59,  -4,  -3, -89, -58, -53, -26])

In [34]:
a1 * a2

array([1092,  390,   96,   28,  570,  759,  630,  155])

In [35]:
a1 / a2

array([0.13186813, 0.09230769, 0.66666667, 0.57142857, 0.06315789,
       0.15942029, 0.15873016, 0.16129032])

In [36]:
# (3 x 2) x (2 x 3) = (3 x 3)

m1 = np.random.randint(1, 10, (3, 2))

In [37]:
m1

array([[1, 4],
       [3, 6],
       [4, 3]])

In [40]:
m2 = np.random.randint(1, 10, (2, 3))
m2

array([[3, 7, 7],
       [4, 7, 1]])

In [42]:
m1.dot(m2)

array([[19, 35, 11],
       [33, 63, 27],
       [24, 49, 31]])

In [45]:
m1 = np.ones((3, 2))
m2 = np.ones((2, 3))

print(m1)
print(m2)
m1.dot(m2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

### Comparações

In [48]:
a1 = np.array([1, 2, 2, 1])
a2 = np.array([1, 2, 2, 1])

#a1 == a2
np.array_equal(a1, a2)

True

In [49]:
np.sin(a1)

array([0.84147098, 0.90929743, 0.90929743, 0.84147098])

In [50]:
np.sum(a2)

6

In [51]:
np.mean(a1)

1.5

In [52]:
np.var(a1)

0.25

In [53]:
np.std(a1)

0.5

In [ ]:
import math

np.log(10)